events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('events_home/', views.events_home_view, name='events_home'),
    path('add/', views.event_add_view, name='events_add'),
    path('image/<int:event_id>/', views.event_image_view, name='events_image'),
    path('detail/<int:event_id>/',views.events_detail_view,name='events_detail'),
    path('edit/<int:event_id>',views.events_edit_view,name='events_edit'),
    path('delete/<int:event_id>',views.events_delete_view,name='events_delete'),
    path('detail/<int:event_id>/goods/', views.goods_detail_view, name='goods_detail'),
    path('<int:event_id>/goods/<int:goods_id>/plus/', views.goods_plus_view, name='goods_plus'),
    path('<int:event_id>/goods/<int:goods_id>/minus/', views.goods_minus_view, name='goods_minus'),
]

goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'

urlpatterns = [
    path("goods_home/",views.goods_home_view,name="goods_home"),
    path("goods_add",views.goods_add_view,name="goods_add"),
    path('goods/<int:event_id>/add/',views.goods_id_add_view,name="goods_id_add"),
    path('events/<int:event_id>/edit/<int:goods_id>/', views.goods_edit_view, name='goods_edit'),
    path('events/<int:event_id>/delete/<int:goods_id>/', views.goods_delete_view, name='goods_delete'),
]

oshikatu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'), 
    path('home/', views.home_view, name='home'),
    path('accounts/', include('accounts.urls')), 
    path('calender/', include('calender.urls')),
    path('events/', include('events.urls')),
    path('plan/', include('plan.urls')),
    path('oshis/', include('oshis.urls')),
    path('money/',include('money.urls')),
    path('goods/', include('goods.urls')),
    path('settings/', views.settings_view, name='settings'),
    path('test/', views.test_view, name='test'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("plan_home/",views.plan_home_view,name="plan_home")
]

events/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    oshi_id = models.ForeignKey(
        'oshis.Oshi',
        on_delete=models.CASCADE,
        related_name='events',
        null=True,
        blank=True
    )
    date = models.DateField()
    location = models.CharField(
        max_length=200,
        null=True,
        blank=True
    )
    event_image = models.ImageField(
        upload_to='event_images/',
        null=True,
        blank=True,
        )
    goods_image = models.ImageField(
        upload_to = 'goods_list_images/',
        null = True,
        blank = True,
    )
    memo = models.TextField(null=True,blank=True)
    
    def total_price(self):
        return sum(goods.total_price for goods in self.goods.all())
    
    def __str__(self):
        return self.title

events/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            'title',
            'oshi_id',
            'date',
            'location',
            'event_image',
            'goods_image',
            'memo',
        ]
        labels = {
            'title': 'イベント名',
            'oshi_id': '推し',
            'date': '日付',
            'location': '場所',
            'event_image': 'イベント画像',
            'goods_image':'グッズ者写真',
            'memo': '説明',
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder':'＊必須'}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'memo': forms.Textarea(attrs={'rows': 3}),
        }

events/views.py
from django.shortcuts import render, redirect
from .models import Event
from goods.models import Goods
from .forms import EventForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

# Create your views here.
@login_required
def events_home_view(request):
    records = Event.objects.filter(user=request.user).order_by('-date')
    return render(request, 'events/events_home.html', {'records': records})

@login_required
def event_add_view(request):
    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()
            return redirect('events:events_home')
    else:
        form = EventForm()
    return render(
        request,
        "events/events_add.html",
        {
            'form':form
        })

@login_required
def event_image_view(request, event_id):
    event = get_object_or_404(Event,event_id=event_id, user=request.user)
    event_id = event.event_id
    event_image = event.event_image

    return render(
        request,
        'events/events_image.html', 
        {
        'event': event,
        'event_id': event_id,
        'event_image':event_image,
    }
    )
@login_required
def events_detail_view(request,event_id):
    event = get_object_or_404(Event,event_id=event_id, user=request.user)
    return render(
        request,
        'events/events_detail.html',
        {
            'event':event,
            'event_id':event.event_id
        }
    )

@login_required
def events_edit_view(request, event_id):
    event = get_object_or_404(Event,event_id=event_id, user=request.user)

    if request.method == "POST":
        form = EventForm(request.POST, request.FILES,instance = event)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()
            return redirect('events:events_detail',event_id = event_id)
    else:
        form = EventForm(instance = event)
    return render(
        request,
        'events/events_edit.html',
        {
            'event':event,
            'event_id':event.event_id,
            'form':form
        }
    )

@login_required
def events_delete_view(request, event_id):
    event = get_object_or_404(Event,event_id=event_id, user=request.user)
    if request.method == "POST":
        event.delete()
        return redirect("events:events_home")
    
    return render(
        request,
        'events/events_delete.html',
        {
            'event':event,
            'event_id':event_id
        }
    )

@login_required
def goods_detail_view(request,event_id):
    event = get_object_or_404(Event,event_id=event_id, user=request.user)
    goods = Goods.objects.filter(user=request.user,event_id=event_id).order_by('goods_id')
    
    events_dict = {}

    for item in goods:
        event_name = item.event.title

        if event_name not in events_dict:
            events_dict[event_name] = {
                "goods_list": [],
                "goods_total": 0,
                "event_id": item.event_id,
            }

        events_dict[event_name]["goods_list"].append({
            "goods_name": item.goods_name,
            "price": item.price,
            "num": item.num,
            "total_price": item.total_price,
            "goods_id":item.goods_id
        })

        events_dict[event_name]["goods_total"] += item.total_price
    return render (request,"events/goods_detail.html",{"goods":goods,"event":event,"events_dict":events_dict,})

@login_required
def goods_plus_view(request, event_id, goods_id):
    goods = get_object_or_404(
        Goods,
        goods_id=goods_id,
        event__event_id=event_id,
        user=request.user
    )
    goods.num += 1
    goods.save()
    return redirect('events:goods_detail', event_id=event_id)

@login_required
def goods_minus_view(request, event_id, goods_id):
    goods = get_object_or_404(
        Goods,
        goods_id=goods_id,
        event__event_id=event_id,
        user=request.user
    )
    if goods.num > 1:
        goods.num -= 1
        goods.save()
    return redirect('events:goods_detail', event_id=event_id)

events/templates/events/events_add.html
{% extends 'base.html' %}

{% block title %}
イベント追加
{% endblock %}

{% block content %}
    <div class="content">
        <form method="post" enctype="multipart/form-data" class="forms">
            {% csrf_token %}
            <div class="form-row">
                <label for="id_title">タイトル</label>
                {{ form.title }}
            </div>

            <div class="form-row">
                <label for="id_oshi_id">推し</label>
                {{ form.oshi_id }}
            </div>


            <div class="form-row side-row">
                <div>
                    <label for="id_date">日付</label>
                    {{ form.date }}
                </div>
                <div>
                    <label for="id_location">場所</label>
                    {{ form.location }}
                </div>
            </div>

            <div class="form-row">
                <label for="id_memo">メモ</label>
                {{ form.memo }}
            </div>

            <div class="form-row file-row">
                <label for="id_event_image">画像</label>
                {{ form.event_image }}
            </div>

            <button class="submit-btn" type="submit">送信</button>

        </form>
    </div>
{% endblock %}

events/templates/events/events_delete.html
{% extends 'base.html' %}

{% block title %}
イベント削除
{% endblock %}

{% block content %}
<div class="content">
    <div class="delete-page">
        <h2>{{ event }}を削除しますか？</h2>

        <p>
            <span class="notemessage">＊削除すると元に戻せません。</span>
        </p>
        <div class="buttons">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="delete-btn">削除</button>
            </form>
            <a href="{% url 'events:events_detail' event.event_id %}">
                <button>キャンセル</button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

events/templates/events/events_detail.html
{% extends 'base.html' %}

{% block title %}
イベント詳細
{% endblock %}

{% block content %}
<div class="content">
    <div class="event">
        <div class="events-button">
            <a href="{% url 'events:events_home' %}" class="back-btn">
                <button>戻る</button>
            </a>
            <a href="{% url 'events:events_image' event.event_id %}">
                <button>画像</button>
            </a>
            <a href="{% url 'events:events_detail' event.event_id %}">
                <button>詳細</button>
            </a>
            <a href="{% url 'events:goods_detail' event.event_id %}">
                <button>グッズ</button>
            </a>
        </div>
        <div class="tables">
            <div class="table-title">
                <h2>{{ event }}</h2>
            </div>
            <div class="element">
                <div class="detail-row">
                    <h5 class="label">推し</h5>
                    {% if event.oshi_id %}
                        <h5>{{ event.oshi_id }}</h5>
                    {% else %}
                        <h5>設定されていません</h5>
                    {% endif %}
                </div>
                <div class="detail-row">
                    <h5 class="label">場所</h5>
                    {% if event.location %}
                        <h5 class="value">{{ event.location }}</h5>
                    {% else %}
                        <h5>設定されていません</h5>
                    {% endif %}
                </div>
                <div class="detail-row">
                    <h5 class="label">日時</h5>
                    <h5 class="value">{{ event.date|date:"Y年m月d日" }}</h5>
                </div>
                <div class="detail-row">
                    <h5 class="label">メモ</h5>
                    <h5 class="value">{{ event.memo }}</h5>
                </div>
            </div>
            
            <div class="buttons">
                <a href="{% url 'events:events_edit' event.event_id %}">
                    <button>編集</button>
                </a>
                <a href="{% url 'events:events_delete' event.event_id %}">
                    <button>削除</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

events/templates/events/events_edit.html
{% extends 'base.html' %}

{% block title %}
イベント編集
{% endblock %}

{% block content %}
    <div class="content">
        <div class="event">
            <div class="events-button">
                <div class="operation-button">
                    <a href="{% url 'events:events_detail' event.event_id %}" class="back-btn">
                        <button>戻る</button>
                    </a>
                </div>
            </div>

            <form method="post" enctype="multipart/form-data" class="forms event-form">
                {% csrf_token %}
                <div class="form-row side-row">
                    <div>
                        <label for="id_title">タイトル</label>
                        {{ form.title }}
                    </div>
                    <div >
                        <label for="id_oshi_id">推し</label>
                        {{ form.oshi_id }}
                    </div>
                </div>

                <div class="form-row side-row">
                    <div>
                        <label for="id_date">日付</label>
                        {{ form.date }}
                    </div>
                    <div>
                        <label for="id_location">場所</label>
                        {{ form.location }}
                    </div>
                </div>

                <div class="form-row">
                    <label for="id_memo">メモ</label>
                    {{ form.memo }}
                </div>

                <div class="form-row file-row">
                    <label for="id_event_image">画像</label>
                    {{ form.event_image }}
                </div>

                <button class="submit-btn" type="submit">送信</button>

            </form>
        </div>
    </div>

{% endblock %}

events/templates/events/events_home.html
{% extends 'base.html' %}

{% block title %}
イベント
{% endblock %}

{% block content %}
    <div class="content">
        <div class="table">
            <table cellspacing="0" cellpadding="5" class="records">
                <thead>
                    <tr>
                        <th>タイトル</th>
                        <th>場所</th>
                        <th>日付</th>
                        <th>詳細</th>
                    </tr>
                </thead>
                <tbody>
                    {% for record in records %}
                    <tr>
                        <td>{{ record.title }}</td>
                        <td>
                            {% if record.location %}
                                {{ record.location }}
                            {% else %}
                                未登録
                            {% endif %}
                        </td>
                        <td>{{ record.date|date:"m/d" }}</td>
                        <td>
                            <a href="{% url 'events:events_image' record.event_id %}">→</a>
                        </td>

                    </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3">データがありません</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

events/templates/events/events_image.html
{% extends 'base.html' %}

{% block title %}
イベント画像
{% endblock %}

{% block content %}
<div class="content">
    <div class="event">
        <div class="events-button">
            <a href="{% url 'events:events_home' %}" class="back-btn">
                <button>戻る</button>
            </a>
            <a href="{% url 'events:events_image' event.event_id %}">
                <button>画像</button>
            </a>
            <a href="{% url 'events:events_detail' event.event_id %}">
                <button>詳細</button>
            </a>
            <a href="{% url 'events:goods_detail' event.event_id %}">
                <button>グッズ</button>
            </a>
        </div>
        <div class="tables">
            <div class="table-title">
                <h2>{{ event.title }}</h2>
            </div>
            <div class="element">
                {% if event_image %}
                    <img src="{{ event_image.url }}" alt="{{ event.title }}" class="event_image">
                {% else %}
                    <h2>画像が登録されていません</h2>
                {% endif %}
                {% if goods_iamge %}
                    <img src="{{ goods_image.url }}" alt="{{ event.title }}" class="event_image">
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

events/templates/events/goods_detail.html
{% extends 'base.html' %}

{% block title %}
グッズ詳細
{% endblock %}

{% block content %}
    <div class="content">
        <div class="event">
            <div class="events-button">
                <a href="{% url 'events:events_home' %}" class="back-btn">
                    <button>戻る</button>
                </a>
                <a href="{% url 'events:events_image' event.event_id %}">
                    <button>画像</button>
                </a>
                <a href="{% url 'events:events_detail' event.event_id %}">
                    <button>詳細</button>
                </a>
                <a href="{% url 'events:goods_detail' event.event_id %}">
                    <button>グッズ</button>
                </a>
            </div>
            <div class="tables">
                <div class="table-title">
                    <h2>{{ event.title }}</h2>
                </div>
                {% if events_dict %}
                    <div class="table">
                        <table cellspacing="0" cellpadding="5" class="records">
                            <thead>
                                <tr>
                                    <th>種類</th>
                                    <th>単価</th>
                                    <th>個数</th>
                                    <th>金額</th>
                                    <th>変更</th>
                                </tr>
                            </thead>
                            {% for event_name, event_data in events_dict.items %}
                                <tbody>
                                    {% for goods in event_data.goods_list %}
                                        <tr>
                                            <td class="goods-name">{{ goods.goods_name }}</td>
                                            <td class="price">{{ goods.price }}円</td>
                                            <td>
                                                <div class="num-control">
                                                    <a href="{% url 'events:goods_minus' event.event_id goods.goods_id %}">-</a>
                                                    <span class="change-num">{{ goods.num }}</span>
                                                    <a href="{% url 'events:goods_plus' event.event_id goods.goods_id %}">+</a>
                                                </div>
                                            </td>
                                            <td class="price">{{ goods.total_price }}円</td>
                                            <td>
                                                <a href="{% url 'goods:goods_edit' event.event_id goods.goods_id %}">→</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th></th>
                                        <th colspan="2">合計金額</th>
                                        <th class="price">{{ event_data.goods_total }}円</th>
                                    </tr>
                                </tfoot>
        {% endfor %}
                        </table>
                    </div>
                {% else %}
                    <h2>グッズが登録されていません</h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}