money/urls.py
from django.urls import path
from . import views

app_name = 'money'

urlpatterns = [
    path('money_home/',views.money_home_view,name="money_home"),

    path('income/',views.income_view,name="income"),
    path('income/edit/<int:pk>/',views.income_edit_view,name="income_edit"),
    path('income/delete/<int:pk>/',views.income_delete_view,name="income_delete"),

    path('expenditure/',views.expenditure_view,name="expenditure"),
    path('expenditure/edit/<int:pk>/',views.expenditure_edit_view,name="expenditure_edit"),
    path('expenditure/delete/<int:pk>/',views.expenditure_delete_view,name="expenditure_delete"),
]

oshikatu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'), 
    path('home/', views.home_view, name='home'),
    path('accounts/', include('accounts.urls')), 
    path('calender/', include('calender.urls')),
    path('events/', include('events.urls')),
    path('plan/', include('plan.urls')),
    path('oshis/', include('oshis.urls')),
    path('money/',include('money.urls')),
    path('goods/', include('goods.urls')),
    path('settings/', views.settings_view, name='settings'),
    path('test/', views.test_view, name='test'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("plan_home/",views.plan_home_view,name="plan_home")
]

money/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class TypeChoices(models.TextChoices):
    SALARY = 'salary','給料'
    BONUS = 'bonus','ボーナス'
    GIFT = 'gift','ギフト'
    OTHER = 'other','その他'

class Income(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    type = models.CharField(
        max_length=20,
        choices=TypeChoices.choices
    )
    amount = models.DecimalField(max_digits=10, decimal_places=0)
    date = models.DateField()

    def __str__(self):
        return f"{self.type} - {self.amount}円"

class GoodsCategory(models.TextChoices):
    GOODS = 'goods',"グッズ",
    SUPERCHAT = 'superchat','スパチャ'
    OTHER = "other","その他"

class Expenditure(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=10, decimal_places=0)
    date = models.DateField()
    memo = models.TextField(blank = True)
    category = models.CharField(
        max_length=20,
        choices = GoodsCategory.choices
    )

    def __str__(self):
        return f"{self.title} - {self.amount}円"

money/forms.py
from django import forms
from .models import Income,Expenditure

class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = [
            'amount',
            'type',
            'date',
        ]
        label = {
            'amount': '金額',
            'type': '種類',
            'date': '日付'
        }
        widgets = {
            'amount': forms.TextInput(attrs={'placeholder':'＊必須'}),
            'date' : forms.DateInput(attrs={'type':'date'}),
        }

class ExpenditureForm(forms.ModelForm):
    class Meta:
        model = Expenditure
        fields = [
            'title',
            'amount',
            'date',
            'category',
            'memo',
        ]
        label = {
            'title':'内容',
            'amount': '金額',
            'date': '日付',
            'category': 'カテゴリー',
            'memo': 'メモ'
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder':'＊必須'}),
            'amount': forms.TextInput(attrs={'placeholder':'＊必須'}),
            'date' : forms.DateInput(attrs={'type':'date'}),
            'memo': forms.Textarea(attrs={'rows': 3}),
        }

money/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from money.models import Income,Expenditure
from .forms import IncomeForm,ExpenditureForm

# Create your views here.
# ホーム
@login_required
def money_home_view(request):
    incomes = Income.objects.filter(user = request.user).order_by('-date')
    expenditures = Expenditure.objects.filter(user = request.user).order_by('-date')

    records = []

    for inc in incomes:
        records.append({
            'model': 'income',
            'pk': inc.pk,
            'type': '収入',
            'date': inc.date,
            'amount': inc.amount,
        })

    for exp in expenditures:
        records.append({
            'model': 'expenditure',
            'pk': exp.pk,
            'type': '支出',
            'date': exp.date,
            'amount': exp.amount,
        })

    records.sort(key=lambda x: x['date'], reverse=True)

    return render(
        request,
        'money/money_home.html',
        {
            'records': records
        })

# 収入
@login_required
def income_view(request):
    if request.method == "POST":
        form = IncomeForm(request.POST, request.FILES)
        if form.is_valid():
            income = form.save(commit=False)
            income.user = request.user
            income.save()
            return redirect('money:money_home')
    else:
        form = IncomeForm()
    return render(
        request,
        "money/income.html",
        {
            'form':form
        })

@login_required
def income_edit_view(request,pk):
    income = get_object_or_404(Income,pk = pk, user = request.user)

    if request.method == "POST":
        form = IncomeForm(request.POST, instance = income)
        if form.is_valid():
            form.save()
            return redirect('money:money_home')
    else:
        form = IncomeForm(instance = income)
    
    return render(
        request,
        'money/income_edit.html',
        {
            'form':form,
            'income':income,
        })

@login_required
def income_delete_view(request,pk):
    income = get_object_or_404(Income, pk = pk, user = request.user)

    if request.method == 'POST':
        income.delete()
        return redirect('money:money_home')

    return render(
        request,
        'money/income_delete.html',
        {
            'income':income,
        }
    )


# 支出
@login_required
def expenditure_view(request):
    if request.method == "POST":
        form = ExpenditureForm(request.POST, request.FILES)
        if form.is_valid():
            expenditure = form.save(commit=False)
            expenditure.user = request.user
            expenditure.save()
            return redirect('money:money_home')
    else:
        form = ExpenditureForm()
    return render(
        request,
        "money/expenditure.html",
        {
            'form':form
        })

@login_required
def expenditure_edit_view(request,pk):
    expenditure = get_object_or_404(Expenditure,pk = pk,user = request.user)

    if request.method == "POST":
        form = ExpenditureForm(request.POST, instance = expenditure)
        if form.is_valid():
            form.save()
            return redirect('money:money_home')
    else:
        form = ExpenditureForm(instance = expenditure)

    return render(
        request,
        'money/expenditure_edit.html',
        {
            'expenditure':expenditure,
            'form':form,
        }
    )


@login_required
def expenditure_delete_view(request, pk):
    expenditure = get_object_or_404(Expenditure, pk = pk, user = request.user)

    if request.method == 'POST':
        expenditure.delete()
        return redirect('money:money_home')
    
    return render(
        request,
        'money/expenditure_delete.html',
        {
            'expenditure':expenditure,
        }
    )

money/templates/money/expenditure.html
{% extends 'base.html' %}

{% block title %}
支出
{% endblock %}


{% block content %}
    <div class="content">
        <form method="post" enctype="multipart/form-data" class="forms">
            {% csrf_token %}
            <div class="form-row">
                <label for="id_title">内容</label>
                {{ form.title }}
            </div>
            <div class="form-row side-row">
                <div>
                    <label for="id_amount">金額</label>
                    {{ form.amount }}
                </div>
                <div>
                    <label for="id_category">カテゴリー</label>
                    {{ form.category }}
                </div>
            </div>
            <div class="form-row">
                <label for="id_date">日付</label>
                {{ form.date }}
            </div>
            <div class="form-row">
                <label for="id_memo">メモ</label>
                {{ form.memo }}
            </div>

            <button class="submit-btn" type="submit">送信</button>

        </form>
        <div class="buttons">
            <div class="text-center bm-3">
                <a href="{% url 'money:money_home' %}">
                    <button>戻る</button>
                </a>
            </div>
            <div class="text-center bm-3">
                <a href="{% url 'money:income' %}">
                    <button type="submit">収入</button>
                </a>
            </div>
            <div class="text-center bm-3">
                <a href="{% url 'money:expenditure' %}">
                    <button type="submit">支出</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

money/templates/money/expenditure_delete.html
{% extends 'base.html' %}

{% block title %}
支出削除
{% endblock %}

{% block content %}
    <div class="content">
        <div class="delete-page">

            <p>{{ expenditure }}を削除しますか？</p>

            <p>
                <span class="notemessage">＊削除すると元に戻せません。</span>
            </p>
            <div class="buttons">
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="delete-btn">削除</button>
                </form>
                <a href="{% url 'money:expenditure_edit' expenditure.pk %}">
                    <button>キャンセル</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

money/templates/money/expenditure_edit.html
{% extends 'base.html' %}

{% block title %}
支出編集
{% endblock %}


{% block content %}
    <div class="content">
        <div class="form-content">

            <div class="button-block">
                <a href="{% url 'money:money_home' %}">
                    <button>戻る</button>
                </a>
                <a href="{% url 'money:expenditure_delete' expenditure.pk %}">
                    <button clasas="delete-btn">削除</button>
                </a>
            </div>
            <form method="post" enctype="multipart/form-data" class="forms">
                {% csrf_token %}
                <div class="form-row">
                    <label for="id_title">内容</label>
                    {{ form.title }}
                </div>
                <div class="form-row side-row">
                    <div>
                        <label for="id_amount">金額</label>
                        {{ form.amount }}
                    </div>
                    <div>
                        <label for="id_category">カテゴリー</label>
                        {{ form.category }}
                    </div>
                </div>
                <div class="form-row">
                    <label for="id_date">日付</label>
                    {{ form.date }}
                </div>
                <div class="form-row">
                    <label for="id_memo">メモ</label>
                    {{ form.memo }}
                </div>

                <button class="submit-btn" type="submit">送信</button>

            </form>
        </div>
    </div>
{% endblock %}

money/templates/money/income.html
{% extends 'base.html' %}

{% block title %}
収入
{% endblock %}

{% block content %}
    <div class="content">
        <form method="post" enctype="multipart/form-data" class="forms">
            {% csrf_token %}
            <div class="form-row">
                <label for="id_amount">金額</label>
                {{ form.amount }}
            </div>
            <div class="form-row">
                <label for="id_type">種類</label>
                {{ form.type }}
            </div>

            <div class="form-row">
                <label for="id_date">日付</label>
                {{ form.date }}
            </div>

            <button class="submit-btn" type="submit">送信</button>

        </form>
        <div class="buttons">
            <div class="text-center bm-3">
                <a href="{% url 'money:money_home' %}">
                    <button>戻る</button>
                </a>
            </div>
            <div class="text-center bm-3">
                <a href="{% url 'money:income' %}">
                    <button type="submit">収入</button>
                </a>
            </div>
            <div class="text-center bm-3">
                <a href="{% url 'money:expenditure' %}">
                    <button type="submit">支出</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

money/templates/money/income_delete.html
{% extends 'base.html' %}

{% block title %}
収支削除
{% endblock %}

{% block content %}
<div class="content">
    <div class="delete-page">

        <p>{{ income }}を削除しますか？</p>

        <p>
            <span class="notemessage">＊削除すると元に戻せません。</span>
        </p>
        <div class="buttons">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="delete-btn">削除</button>
            </form>
            <a href="{% url 'money:income_edit' income.pk %}">
                <button>キャンセル</button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

money/templates/money/income_edit.html
{% extends 'base.html' %}

{% block title %}
収入編集
{% endblock %}

{% block content %}
    <div class="content">
        <div class="form-content">
            <div class="button-block">
                <a href="{% url 'money:money_home' %}">
                    <button>戻る</button>
                </a>
                <a href="{% url 'money:income_delete' income.pk %}">
                    <button clasas="delete-btn">削除</button>
                </a>
            </div>
            <form method="post" enctype="multipart/form-data" class="forms">
                {% csrf_token %}
                <div class="form-row">
                    <label for="id_amount">金額</label>
                    {{ form.amount }}
                </div>
                <div class="form-row">
                    <label for="id_type">種類</label>
                    {{ form.type }}
                </div>

                <div class="form-row">
                    <label for="id_date">日付</label>
                    {{ form.date }}
                </div>

                <button class="submit-btn" type="submit">送信</button>

            </form>
        </div>
    </div>
{% endblock %}

money/templates/money/money_home.html
{% extends 'base.html' %}

{% block title %}
収支管理
{% endblock %}

{% block content %}
    <div class="content">
        <div class="tables money">
            <div class="table-title">
                <h3>収支</h3>
            </div>
            <div class="table">
                <table cellspacing="0" cellpadding="5" class="records">
                    <thead>
                        <tr>
                            <th>種類</th>
                            <th>日付</th>
                            <th>金額</th>
                            <th>変更</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record in records %}
                        <tr>
                            <td>{{ record.type }}</td>
                            <td>{{ record.date|date:"Y/m/d" }}</td>
                            <td class="price">{{ record.amount }}円</td>

                        <td>
                            {% if record.model == 'income' %}
                                <a href="{% url 'money:income_edit' record.pk %}" class="a-black">→</a>
                            {% else %}
                                <a href="{% url 'money:expenditure_edit' record.pk %}" class="a-black">→</a>
                            {% endif %}
                        </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="3">データがありません</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="buttons">
            <div class="text-center bm-3">
                <a href="{% url 'money:income' %}">
                    <button type="submit">収入</button>
                </a>
            </div>
            <div class="text-center bm-3">
                <a href="{% url 'money:expenditure' %}">
                    <button type="submit">支出</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}