oshikatu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'), 
    path('home/', views.home_view, name='home'),
    path('accounts/', include('accounts.urls')), 
    path('calender/', include('calender.urls')),
    path('events/', include('events.urls')),
    path('plan/', include('plan.urls')),
    path('oshis/', include('oshis.urls')),
    path('money/',include('money.urls')),
    path('goods/', include('goods.urls')),
    path('settings/', views.settings_view, name='settings'),
    path('test/', views.test_view, name='test'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oshis/urls.py
from django.urls import path
from . import views

app_name = 'oshis'

urlpatterns = [
    path('oshis_home/', views.oshi_home_view, name='oshi_home'),
    path('oshi_add/', views.oshi_add_view, name='oshi_add'),
    path('oshi_detail/<int:pk>/',views.oshi_detail_view,name="oshi_detail"),
    path('oshi_edit/<int:pk>/',views.oshi_edit_view,name="oshi_edit"),
    path('oshi_delete/<int:pk>/', views.oshi_delete_view, name="oshi_delete"),
]

plan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("plan_home/",views.plan_home_view,name="plan_home")
]

oshis/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.
class OshiCategory(models.TextChoices):
    ARTUST="artist","アーティスト"
    ACTIVIST = "activist","配信者"
    VOCALOID = "vocaloid","ボーカロイド"
    CHARACTER = "character","キャラクター"
    VTUBER = "vtuber","Vチューバー"
    IDOL= "idol","アイドル"
    PERFORMER = "performer","演者"
    OTHER = "other","その他"

class Oshi(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name=('oshis')
        )
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=7, default="#666666")
    group_name = models.CharField(max_length=20,null = True,blank = True)
    birthday = models.DateField(null=True, blank=True)
    aniversary = models.DateField(null=True,blank=True)
    met_day = models.DateField(
        null = True,
        blank=True,
        default=timezone.now
        )
    input_formats = ['%m-%d']

    category = models.CharField(
        max_length=20,
        choices = OshiCategory.choices,
        default='未設定'
    )
    image = models.ImageField(upload_to = 'oshi_icons/',null=True,blank=True)
    notes = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

oshis/forms.py
from django import forms
from .models import Oshi

class OshiForm(forms.ModelForm):
    class Meta:
        model = Oshi
        fields = [
            'name',
            'color',
            'group_name',
            'birthday',
            'aniversary',
            'met_day',
            'category',
            'image',
            'notes',
        ]
        labels = {
            'name': '名前',
            'color':'カラー',
            'group_name': 'グループ名',
            'birthday': '誕生日',
            'aniversary': '記念日',
            'met_day': '出会った日',
            'category': 'カテゴリ',
            'image': '画像',
            'notes': 'メモ',
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': '＊必須'}),
            'color': forms.TextInput(attrs={'type': 'color'}),
            'birthday': forms.DateInput(attrs={'type': 'date'}),
            'aniversary': forms.DateInput(attrs={'type': 'date'}),
            'met_day': forms.DateInput(attrs={'type': 'date'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'notes': forms.Textarea(attrs={'rows': 3}),
        }
        input_formats = ['%m月%d日']

oshis/views.py
from django.shortcuts import render, redirect, get_object_or_404
from oshis.models import Oshi
from .forms import OshiForm
from django.contrib.auth.decorators import login_required
from datetime import date

# Create your views here.
@login_required
def oshi_home_view(request):
    oshis = Oshi.objects.all()
    return render(request, 'oshis/oshi_home.html', {'oshis': oshis})

@login_required
def oshi_add_view(request):
    if request.method == 'POST':
        form = OshiForm(request.POST, request.FILES)
        if form.is_valid():
            oshi = form.save(commit=False)
            oshi.user = request.user
            oshi.save()
            return redirect('oshis:oshi_home')
    else:
        form = OshiForm()
    return render(request, 'oshis/oshi_add.html', {'form': form})

def oshi_detail_view(request, pk):
    oshi = get_object_or_404(Oshi, pk=pk, user=request.user)
    days_elapsed = 0
    if oshi.met_day:
        today = date.today()
        days_elapsed = (today - oshi.met_day).days

    if days_elapsed >= 3650:
        rank = "mythic"
    elif days_elapsed >= 1000:
        rank = "legend"
    elif days_elapsed >= 365:
        rank = "gold"
    elif days_elapsed >= 100:
        rank = "silver"
    else:
        rank = "bronze"

    return render(
        request,
        'oshis/oshi_detail.html',
        {
            'oshi': oshi,
            'days_elapsed':days_elapsed,
            'rank':rank,
        }
        )

@login_required
def oshi_edit_view(request,pk):
    oshi = get_object_or_404(Oshi,pk = pk, user=request.user)

    if request.method == 'POST':
        form = OshiForm(request.POST, request.FILES, instance=oshi)
        if form.is_valid():
            form.save()
            return redirect('oshis:oshi_detail',pk=pk)
    else:
        form = OshiForm(instance=oshi)
    return render(
        request, 
        'oshis/oshi_edit.html', 
        {
            'form': form,
            "oshi":oshi
        })

@login_required
def oshi_delete_view(request,pk):
    oshi = get_object_or_404(Oshi, pk=pk)

    if request.method == "POST":
        oshi.delete()
        return redirect("oshis:oshi_home")

    return render(
        request,
        "oshis/oshi_delete.html",
        {"oshi": oshi}
    )

oshis/templates/oshis/oshi_add.html
{% extends 'base.html' %}

{% block title %}
推しを追加
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="forms">
    {% csrf_token %}

    <h2 class="form-title">推しを追加</h2>

    <div class="form-row side-row">
        <div>
            <label for="id_name">名前</label>
            {{ form.name }}
        </div>
        <div>
            <label for="id_group_name">グループ名</label>
            {{ form.group_name }}
        </div>
    </div>

    <div class="form-row side-row">
        <div>
            <label for="id_category">カテゴリ</label>
            {{ form.category }}
        </div>

        <div>
            <label for="id_color">カラー</label>
            {{ form.color }}
        </div>
    </div>
    <div class="form-section">
        <div class="form-row side-row">
            <div>
                <label for="id_birthday">誕生日</label>
                {{ form.birthday }}
            </div>
            <div>
                <label for="id_aniversary">記念日</label>
                {{ form.aniversary }}
            </div>
            <div>
                <label for="id_met_day">出会った日</label>
                {{ form.met_day }}
            </div>
        </div>

        <div class="form-row">
            <label for="id_image">画像</label>
            {{ form.image }}
        </div>

        <div class="form-row">
            <label for="id_notes">メモ</label>
            {{ form.notes }}
        </div>
    </div>

    <button class="submit-btn" type="submit">登録</button>
</form>

        
{% endblock %}

oshis/templates/oshis/oshi_delete.html
{% extends 'base.html' %}

{% block title %}
削除ページ
{% endblock %}

{% block content %}
    <div class="content">
        <div class="delete-page">
            <h2>{{ oshi.name }}を削除しますか？</h2>

            <p>
                <span class="notemessage">＊削除すると元に戻せません。</span>
            </p>
            <div class="buttons">
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="delete-btn">削除</button>
                </form>
                <a href="{% url 'oshis:oshi_detail' oshi.id %}">
                    <button>キャンセル</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

oshis/templates/oshis/oshi_detail.html
{% extends 'base.html' %}

{% block title %}
{{ oshi.name }}の詳細
{% endblock %}

{% block content %}
    <div class="content">
        <div class="oshi-detail" style="--oshi-color: {{ oshi.color }};">
            <div>
                <a href="{% url 'oshis:oshi_home' %}">
                <button>戻る</button>
            </a>
            </div>
            <div class="info">
                {% if oshi.image %}
                    <img src="{{ oshi.image.url }}" alt="{{ oshi.name }}の写真" class="oshi_detail_image">
                {% endif %}

                <div class="name-detail">
                    <p>{{ oshi.get_category_display }}：</p>
                    <h2 class="oshi-name">{{ oshi.name}}</h2>
                </div>
                {% if oshi.group %}
                    <p>所　属：{{ oshi.group }}</p>
                {% else %}
                    <p>所　属：所属が登録されていません</p>
                {% endif %}
                <p>誕生日：{{ oshi.birthday|date:"m月d日" }}</p>

                {% if oshi.aniversary %}
                    <p>周年日：{{ oshi.aniversary|date:"m月d日" }}</p>
                {% else %}
                    <p>周年日：未登録</p>
                {% endif %}
                
                <p class="days-label">出会ってから</p>
                <p class="days-count">
                    <span
                    id="days-counter"
                    class="days {{ rank }}"
                    data-target="{{ days_elapsed }}">
                    0
                    </span>日経過
                </p>

                <p>メモ</p>
                <p class="memo">
                    {% if oshi.notes %}
                        {{ oshi.notes }}
                    {% else %}
                        まだなにも書かれていません。
                    {% endif  %}
                </p>
                <div class="buttons">
                    <a href="{% url 'oshis:oshi_edit' oshi.id %}">
                        <button>編集</button>
                    </a>
                    <a href="{% url 'oshis:oshi_delete' oshi.id %}">
                        <button>削除</button>
                    </a>
                </div>
            </div>
        </div>
        
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const counter = document.getElementById("days-counter");
            const target = Number(counter.dataset.target);
        
            let current = 0;
        
            const duration = 1200;
            const frameRate = 16;
            const step = Math.max(1, Math.floor(target / (duration / frameRate)));
        
            const timer = setInterval(() => {
                current += step;
                if (current >= target) {
                    current = target;
                    clearInterval(timer);
                }
                counter.textContent = current;
            }, frameRate);
        });
        </script>
{% endblock %}

oshis/templates/oshis/oshi_edit.html
{% extends 'base.html' %}

{% block title %}
編集ページ
{% endblock %}

{% block content %}
    <div class="content">
        <div class="oshi-detail">
        <div>
            <a href="{% url 'oshis:oshi_detail' oshi.id %}">
                <button>
                    戻る
                </button>
            </a>
        </div>
        <div class="info">
            <form method="post" enctype="multipart/form-data" class="forms">
                {% csrf_token %}
                <div class="form-row side-row">
                    <div>
                        <label for="id_name">名前</label>
                        {{ form.name }}
                    </div>
                    <div>
                        <label for="id_group_name">グループ名</label>
                        {{ form.group_name }}
                    </div>
                </div>
                <div class="form-row side-row">
                    <div>
                        <label for="id_category">カテゴリ</label>
                        {{ form.category }}
                    </div>
            
                    <div>
                        <label for="id_color">カラー</label>
                        {{ form.color }}
                    </div>
                </div>
            
                <div class="form-row side-row">
                    <div>
                        <label for="id_birthday">誕生日</label>
                        {{ form.birthday }}
                    </div>
                    <div>
                        <label for="id_aniversary">記念日</label>
                        {{ form.aniversary }}
                    </div>
                
                    <div>
                        <label for="id_met_day">出会った日</label>
                    {{ form.met_day }}
                    </div>
                </div>
            

            

                <div class="form-row">
                    <label class="field-label">画像</label>
                    <div class="field-body">
                        {{ form.image }}
                    </div>
                </div>
            
                <div class="form-row">
                    <label for="id_notes">メモ</label>
                    {{ form.notes }}
                </div>
                
                <button class="submit-btn" type="submit">送信</button>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

oshis/templates/oshis/oshi_home.html
{% extends 'base.html' %}

{% block title %}
推し一覧
{% endblock %}

{% block content %}
    <div class="content">
        <div class="oshis">
            {% for oshi in oshis %}
            <a href="{% url 'oshis:oshi_detail' oshi.id %}" class="a-black">
                <div class="oshi" style="--oshi-color: {{ oshi.color }};">
                    <div class="image">
                        {% if oshi.image %}
                            <img src="{{ oshi.image.url }}" alt="{{ oshi.name }}" class="oshi-image">
                        {% else %}
                            <div class="empty-img">
                                <p>画像がありません</p>
                            </div>
                        {% endif %}
                    </div>
                    <div class="oshi-info">
                        <h3>{{ oshi.name }}</h3>
                        <p>誕生日: {{ oshi.birthday|date:'n月j日' }}</p>
                    </div>
                </div>
            </a>
            {% empty %}
                <p>まだ推しが登録されていません。</p>
            {% endfor %}

            
            <div class="oshi_plus">
                <a href="{% url 'oshis:oshi_add' %}">
                    <p>＋</p>
                </a>
            </div>
        </div>
    </div>

    <p>{{ data }}</p>
{% endblock %}