events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('events_home/', views.events_home_view, name='events_home'),
    path('add/', views.event_add_view, name='events_add'),
    path('image/<int:event_id>/', views.event_image_view, name='events_image'),
    path('detail/<int:event_id>/',views.events_detail_view,name='events_detail'),
    path('edit/<int:event_id>',views.events_edit_view,name='events_edit'),
    path('delete/<int:event_id>',views.events_delete_view,name='events_delete'),
    path('detail/<int:event_id>/goods/', views.goods_detail_view, name='goods_detail'),
    path('<int:event_id>/goods/<int:goods_id>/plus/', views.goods_plus_view, name='goods_plus'),
    path('<int:event_id>/goods/<int:goods_id>/minus/', views.goods_minus_view, name='goods_minus'),
]

goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'

urlpatterns = [
    path("goods_home/",views.goods_home_view,name="goods_home"),
    path("goods_add",views.goods_add_view,name="goods_add"),
    path('goods/<int:event_id>/add/',views.goods_id_add_view,name="goods_id_add"),
    path('events/<int:event_id>/edit/<int:goods_id>/', views.goods_edit_view, name='goods_edit'),
    path('events/<int:event_id>/delete/<int:goods_id>/', views.goods_delete_view, name='goods_delete'),
]

oshikatu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'), 
    path('home/', views.home_view, name='home'),
    path('accounts/', include('accounts.urls')), 
    path('calender/', include('calender.urls')),
    path('events/', include('events.urls')),
    path('plan/', include('plan.urls')),
    path('oshis/', include('oshis.urls')),
    path('money/',include('money.urls')),
    path('goods/', include('goods.urls')),
    path('settings/', views.settings_view, name='settings'),
    path('test/', views.test_view, name='test'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("plan_home/",views.plan_home_view,name="plan_home")
]

goods/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator

# Create your models here.
class GoodsCategory(models.TextChoices):
    ACRYLIC_KEYHOLDER = 'acrylic_keyholder', "アクキー"
    ACRYLIC_STAND = 'acrylic_stand', "アクスタ"
    BADGE = 'badge', "缶バッジ"
    FIGURE = 'figure', "フィギュア"
    DISC = 'disc', "CD・DVD・BD"
    BOOK = 'book', "書籍"
    OTHER = "other","その他"

class Goods(models.Model):
    goods_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='goods'
        )
    event = models.ForeignKey(
        'events.Event',
        on_delete=models.CASCADE,
        related_name='goods',
        null=False,
        blank=False,
    )
    goods_name = models.CharField(max_length=20)
    category = models.CharField(
        max_length=20,
        choices=GoodsCategory.choices,
        default=GoodsCategory.OTHER
        )
    price = models.DecimalField(max_digits=10, decimal_places=0)
    num = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        default=1,
        )
    total_price = models.DecimalField(
        editable=False,
        default=0,
        max_digits=10,
        decimal_places=0,
        )
    goods_image = models.ImageField(upload_to='goods_images/', null=True, blank=True)
    memo = models.TextField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.total_price = self.price * self.num
        super().save(*args, **kwargs)

    def __str__(self):
        return self.goods_name

oshis/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.
class OshiCategory(models.TextChoices):
    ARTUST="artist","アーティスト"
    ACTIVIST = "activist","配信者"
    VOCALOID = "vocaloid","ボーカロイド"
    CHARACTER = "character","キャラクター"
    VTUBER = "vtuber","Vチューバー"
    IDOL= "idol","アイドル"
    PERFORMER = "performer","演者"
    OTHER = "other","その他"

class Oshi(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name=('oshis')
        )
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=7, default="#666666")
    group_name = models.CharField(max_length=20,null = True,blank = True)
    birthday = models.DateField(null=True, blank=True)
    aniversary = models.DateField(null=True,blank=True)
    met_day = models.DateField(
        null = True,
        blank=True,
        default=timezone.now
        )
    input_formats = ['%m-%d']

    category = models.CharField(
        max_length=20,
        choices = OshiCategory.choices,
        default='未設定'
    )
    image = models.ImageField(upload_to = 'oshi_icons/',null=True,blank=True)
    notes = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

goods/forms.py
from django import forms
from .models import Goods

class GoodsForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = [
            'event',
            'goods_name',
            'category',
            'price',
            'num',
            'goods_image',
            'memo',
        ]
        labels = {
            'event': 'イベント',
            'goods_name': 'グッズ名',
            'category': 'カテゴリー',
            'price': '価格',
            'num': '個数',
            'goods_image': '画像',
            'memo': 'メモ',
        }
        widgets = {
            'price': forms.NumberInput(attrs={'min': 0}),
            'memo': forms.Textarea(attrs={'rows': 3}),
        }

class GoodsIdForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = [
            'goods_name',
            'category',
            'price',
            'num',
            'goods_image',
            'memo',
        ]
        labels = {
            'goods_name': 'グッズ名',
            'category': 'カテゴリー',
            'price': '価格',
            'num': '個数',
            'goods_image': '画像',
            'memo': 'メモ',
        }
        widgets = {
            'memo': forms.Textarea(attrs={'rows': 3}),
        }

goods/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from events.models import Event
from oshis.models import Oshi
from .models import Goods
from .forms import GoodsForm,GoodsIdForm

# Create your views here.

@login_required
def goods_home_view(request):
    goods = Goods.objects.filter(user=request.user)

    title = request.GET.get("title")
    oshi_id = request.GET.get("oshi")

    if title:
        goods = goods.filter(event__title__icontains=title)

    if oshi_id:
        goods = goods.filter(event__oshi_id=oshi_id)

    goods = goods.order_by("goods_id")

    events_dict = {}

    for item in goods:
        event = item.event

        if event not in events_dict:
            events_dict[event] = {
                "goods_list": [],
                "event_total": 0,
                "event_id": event.event_id,
            }

        events_dict[event]["goods_list"].append({
            "goods_name": item.goods_name,
            "price": item.price,
            "num": item.num,
            "total_price": item.total_price,
            "goods_id": item.goods_id,
        })

        events_dict[event]["event_total"] += item.total_price

    oshis = Oshi.objects.filter(user=request.user)

    return render(
        request,
        "goods/goods_home.html",
        {
            "events_dict": events_dict,
            "oshis": oshis,
        }
    )

@login_required
def goods_add_view(request):
    if request.method =="POST":
        form = GoodsForm(request.POST,request.FILES)
        if form.is_valid():
            goods = form.save(commit=False)
            goods.user = request.user
            goods.save()
            return redirect('goods:goods_home')
    else:
        form = GoodsForm()
    return render (request,"goods/goods_add.html",{"form":form})

@login_required
def goods_id_add_view(request, event_id):
    event = get_object_or_404(Event, event_id=event_id, user=request.user)

    if request.method =="POST":
        form = GoodsIdForm(request.POST,request.FILES)
        if form.is_valid():
            goods = form.save(commit=False)
            goods.user = request.user
            goods.event = event
            goods.save()
            return redirect(
                'events:events_detail',
                event_id = event.event_id
                )
    else:
        form = GoodsIdForm()
    return render (
        request,
        "goods/goods_id_add.html",
        {
            "form": form,
            "event_id": event_id,
            "event": event
            }
        )

@login_required
def goods_edit_view(request, event_id, goods_id):
    event = get_object_or_404(
        Event,
        event_id=event_id,
        user=request.user
    )

    goods = get_object_or_404(
        Goods,
        goods_id=goods_id,
        event__event_id=event_id,
        user=request.user
    )

    if request.method == "POST":
        form = GoodsForm(request.POST, request.FILES, instance=goods)
        if form.is_valid():
            form.save()
            return redirect('events:goods_detail', event_id=event_id)
    else:
        form = GoodsForm(instance=goods)

    return render(
        request,
        'goods/goods_edit.html',
        {
        'form': form,
        'event': event,
        'goods': goods,
        }
        )

@login_required
def goods_delete_view(request, event_id, goods_id):
    event = get_object_or_404(
        Event,
        event_id=event_id,
        user=request.user
    )
    goods = get_object_or_404(
        Goods,
        goods_id=goods_id,
        event__event_id=event_id,
        user=request.user
    )

    if request.method == "POST":
        goods.delete()
        return redirect(
            'events:goods_detail',
            event_id=event_id
            )

    return render(
        request,
        'goods/goods_delete.html',
        {
        'goods': goods,
        'event':event,
        'event_id': event_id,
        }
        )

goods/templates/goods/goods_add.html
{% extends 'base.html' %}

{% block title %}
グッズ追加
{% endblock %}

{% block content %}
    <div class="content">
        <form method="post" enctype="multipart/form-data" class="forms">
            {% csrf_token %}
            <div class="form-row">
                <label for="id_event">イベント</label>
                    {{ form.event }}
            </div>
            <div class="form-row side-row">
                <div>
                    <label for="id_goods_name">グッズ名</label>
                        {{ form.goods_name }}
                </div>
                <div>
                    <label for="id_category">カテゴリー</label>
                        {{ form.category }}
                </div>
            </div>
            <div class="form-row side-row">
                <div>
                    <label for="id_price">価格</label>
                        {{ form.price }}
                </div>
                <div class="form-num">
                    <label for="id_num">個数
                        {{ form.num }}
                    </label>
                </div>
            </div>
            <div class="form-row">
                <label for="id_image">画像</label>
                    {{ form.goods_image }}
            </div>
            <div class="form-row">
                <label for="id_memo">メモ</label>
                    {{ form.memo }}
            </div>

            <button class="submit-btn" type="submit">送信</button>

        </form>
    </div>
{% endblock %}

goods/templates/goods/goods_delete.html
{% extends 'base.html' %}

{% block title %}
グッズ削除
{% endblock %}

{% block content %}
    <div class="content">
        <div class="delete-page">
            <p>{{ goods.goods_name }}を削除しますか？</p>

            <p>
                <span class="notemessage">＊削除すると元に戻せません。</span>
            </p>
            <div class="buttons">
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="delete-btn">削除</button>
                </form>
                <a href="{% url 'goods:goods_edit' event.event_id goods.goods_id %}">
                    <button>キャンセル</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

goods/templates/goods/goods_detail.html
{% extends 'base.html' %}

{% block title %}
グッズ詳細
{% endblock %}

{% block content %}
    <div class="content">
        {% if events_dict %}
            {% for event, data in events_dict.items %}
                <div class="tables">
                    <div class="table goods-detail">
                        <h2 class="table-title">{{ event }}</h2>
                        <table cellspacing="0" cellpadding="5" class="records">
                            <thead>
                                <tr>
                                    <th>種類</th>
                                    <th>単価</th>
                                    <th>個数</th>
                                    <th>金額</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for record in data.goods_list %}
                                    <tr>
                                        <td>{{ record.goods_name }}</td>
                                        <td class="price">{{ record.price }}円</td>
                                        <td class="num">
                                            <div class="num-control">
                                                {{ record.num }}個
                                            </div>
                                        </td>
                                        <td class="price">{{ record.total_price }}円</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="2"></th>
                                    <th>合計金額</th>
                                    <th class="price">{{ data.event_total }}円
                                    </th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>データがありません</p>
        {% endif %}
    {% endblock %}
{% endblock %}

goods/templates/goods/goods_edit.html
{% extends 'base.html' %}

{% block title %}
グッズ編集
{% endblock %}

{% block content %}
    <div class="content">
        <div class="form-content">
            <div class="button-block">
                <a href="{% url 'events:events_detail' event.event_id %}">
                    <button>戻る</button>
                </a>
                <a href="{% url 'goods:goods_delete' event.event_id  goods.goods_id %}">
                    <button clasas="delete-btn">削除</button>
                </a>
            </div>
            <div class="forms">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <label for="id_event">イベント</label>
                            {{ form.event }}
                    </div>

                    <div class="form-row side-row">
                        <div>
                            <label for="id_goods_name">グッズ名</label>
                                {{ form.goods_name }}
                        </div>
                        <div>
                            <label for="id_category">カテゴリー</label>
                                {{ form.category }}
                            </label>
                        </div>
                    </div>
                    <div class="form-row side-row">
                        <div>
                            <label for="id_price">価格</label>
                                {{ form.price }}
                        </div>
                        <div class="form-num">
                            <label for="id_num">個数
                                {{ form.num }}
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <label for="id_image">画像</label>
                            {{ form.goods_image }}
                    </div>
                    <div class="form-row">
                        <label for="id_memo">メモ</label>
                            {{ form.memo }}
                    </div>

                    <button class="submit-btn" type="submit">送信</button>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

goods/templates/goods/goods_home.html
{% extends 'base.html' %}

{% block title %}
グッズ
{% endblock %}

{% block content %}
    <div class="content">
        <div class="forms">
            <form method="get">
                <input
                    type="text"
                    name="title"
                    placeholder="イベント名"
                    value="{{ request.GET.title }}"
                >
            
                <select name="oshi" class="filter-select">
                    <option value="">推しを選択</option>
                    {% for oshi in oshis %}
                        <option
                            value="{{ oshi.id }}"
                            {% if request.GET.oshi == oshi.id|stringformat:"s" %}selected{% endif %}
                        >
                            {{ oshi.name }}
                        </option>
                    {% endfor %}
                </select>
            
                <button type="submit" class="filter-btn">絞り込む</button>
            </form>

        </div>
        <div class="goods-tables">
            {% if events_dict %}
                {% for event, data in events_dict.items %}
                    <div class="table goods-table">
                        <div class="table-title">
                            <h5>{{ event.title }}</h5>
                        </div>
                        <div class="records">
                            <table cellspacing="0" cellpadding="5">
                                <thead>
                                    <tr>
                                        <th>種類</th>
                                        <th>単価</th>
                                        <th>個数</th>
                                        <th>金額</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for record in data.goods_list %}
                                        <tr>
                                            <td class="goods-name">{{ record.goods_name }}</td>
                                            <td class="price">{{ record.price }}円</td>
                                            <td class="num">
                                                <div class="num-control">
                                                    {{ record.num }}個
                                                </div>
                                            </td>
                                            <td class="price">{{ record.total_price }}円</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th></th>
                                        <th colspan="2">合計金額</th>
                                        <th class="price">{{ data.event_total }}円
                                        </th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>データがありません</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

goods/templates/goods/goods_id_add.html
{% extends 'base.html' %}

{% block title %}
グッズ追加
{% endblock %}

{% block content %}
    <div class="content">
        <form method="post" enctype="multipart/form-data" class="forms">
            {% csrf_token %}

            <div class="form-row side-row">
                <div>
                    <label for="id_goods_name">グッズ名</label>
                        {{ form.goods_name }}
                </div>
                <div class="form-row">
                    <label for="id_category">カテゴリー</label>
                        {{ form.category }}
                    </label>
                </div>
            </div>
            <div class="form-row side-row">
                <div>
                    <label for="id_price">価格</label>
                        {{ form.price }}
                </div>
                <div class="form-num">
                    <label for="id_num">個数
                        {{ form.num }}
                    </label>
                </div>
            </div>

            <button class="submit-btn" type="submit">送信</button>

        </form>
    </div>
{% endblock %}